force-app/main/default/objects/F_Leaderboard__c/F_Leaderboard__c.object-meta.xml
<CustomObject>
    <label>Leaderboard</label>
    <nameField>
        <displayFormat>L-{000000000}</displayFormat>
        <label>Leaderboard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaderboard</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/F_Leaderboard__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>End Date</description>
    <label>EndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/F_Leaderboard__c/fields/F_ChatterGroupId__c.field-meta.xml
<CustomField>
    <fullName>F_ChatterGroupId__c</fullName>
    <externalId>true</externalId>
    <label>Chatter Group Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/F_Leaderboard__c/fields/F_User__c.field-meta.xml
<CustomField>
    <fullName>F_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OneX_Leaderboard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/F_Leaderboard__c/fields/LastModifiedPoints__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedPoints__c</fullName>
    <label>LastModifiedPoints</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/F_Leaderboard__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipName>OneX_Leaderboard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/F_Leaderboard__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Start Date</description>
    <label>StartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/F_Leaderboard__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Week</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/F_LeaderboardOrderBatch.cls
global class F_LeaderboardOrderBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    global Integer position;
    public Integer groupIndex;
    public Id groupId;
    public date startDate;
    public string type;
    public List<String> groupCheck;
    
    public F_LeaderboardOrderBatch(Integer index, list<String> groupCheck){
        groupIndex = index;
        this.groupCheck = groupCheck;
        position = 0;
    }
    
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String groupToCheck = groupCheck[groupIndex];
		System.debug('#### groupIndex: ' + groupIndex);
		System.debug('#### Gonna order this list: ' + groupToCheck);
        
		List<String> splitList = groupToCheck.split('@');
        groupId = splitList[0];
        type = splitList[1];
        startDate = Date.valueOf(splitList[2]);
        
        return Database.getQueryLocator( [SELECT Id, F_User__c, F_ChatterGroupId__c, EndDate__c,Member__c, Points__c, Position__c,
                                          StartDate__c, Type__c FROM F_Leaderboard__c WHERE StartDate__c = :startDate
                                          AND F_ChatterGroupId__c = :groupId AND Type__c = :type ORDER BY Points__c DESC, LastModifiedPoints__c] );
        
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        System.debug('##### Execute');
        System.debug('##### List Size ' + scope.Size());
        List<F_Leaderboard__c> leaderboardList = (List<F_Leaderboard__c>) scope;
        List<F_Leaderboard__c> lBoardListUpdate = new List<F_Leaderboard__c>();
        
        for(F_Leaderboard__c lBoardValue : leaderboardList ){
            System.debug('###### position ' + (position+1));
            lBoardValue.Position__c = position+1;
            position++;
            lBoardListUpdate.add(lBoardValue);
        }
        update lBoardListUpdate;
        
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('##### finish');
        
        if(groupIndex+1 < groupCheck.size()){
            System.debug('#### Gonna call this index: ' + (groupIndex+1));
            
            F_LeaderboardOrderBatch lBoard = new F_LeaderboardOrderBatch(groupIndex+1, groupCheck);
            database.executeBatch(lBoard);
        }else{
            System.debug('#### End of all order');
        }
        
    }
    
}