force-app/main/default/objects/Chatter_Event__c/Chatter_Event__c.object-meta.xml
<CustomObject>
    <label>Chatter Event</label>
    <nameField>
        <label>Chatter Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chatter Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chatter_Event__c/fields/Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Group_ID__c</fullName>
    <label>Group ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chatter_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Write a post</fullName>
            </value>
            <value>
                <fullName>Your answer is marked as best</fullName>
            </value>
            <value>
                <fullName>Receive a like</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Transaction__c/fields/Chatter_Event__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Chatter Event</description>
    <label>Chatter Event</label>
    <referenceTo>Chatter_Event__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FieloCommunityActivityDetailsController.cls
public with sharing class FieloCommunityActivityDetailsController {

    @AuraEnabled(cacheable=true)
    public static List<MemberExtractWrapper> getMemberExtractByGroup(String groupId) {
        List<MemberExtractWrapper> memberExtractWrLst= new List<MemberExtractWrapper>();
        for(AggregateResult lAr :[SELECT Chatter_Event__r.Type__c typeEv, COUNT(Id) countPt, SUM(FieloPLT__Points__c) totalPoints
                FROM FieloPLT__Transaction__c
                WHERE Chatter_Event__c != null 
                AND Chatter_Event__r.Group_ID__c = :groupId
                AND FieloPLT__Member__r.FieloPLT__User__c = :UserInfo.getUserId()
                GROUP BY Chatter_Event__r.Type__c]) {
            memberExtractWrLst.add(
                new MemberExtractWrapper(
                    String.valueOf(lAr.get('typeEv')),
                    Integer.valueOf(lAr.get('countPt')),
                    (Decimal)(lAr.get('totalPoints'))
                )
            );
        }
        memberExtractWrLst.sort();
        return memberExtractWrLst;
    }

    public class MemberExtractWrapper implements Comparable {
        @AuraEnabled public String activity;
        @AuraEnabled public Integer count;
        @AuraEnabled public Decimal pointsEarned;

        public MemberExtractWrapper(String aActivity, Integer aCount, Decimal aPointsEarned) {
            this.activity = aActivity;
            this.count = aCount;
            this.pointsEarned = aPointsEarned;
        }

        public Integer compareTo(Object compareTo) {
            MemberExtractWrapper compareToAct = (MemberExtractWrapper)compareTo;
            if (activity == compareToAct.activity) return 0;
            if (activity > compareToAct.activity) return 1;
            return -1;        
        }
    }
}