force-app/main/default/objects/Chatter_Event__c/Chatter_Event__c.object-meta.xml
<CustomObject>
    <label>Chatter Event</label>
    <nameField>
        <label>Chatter Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chatter Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chatter_Event__c/fields/Feed_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Feed_Item_Id__c</fullName>
    <externalId>true</externalId>
    <label>Feed Item Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chatter_Event__c/fields/Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Group_ID__c</fullName>
    <label>Group ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chatter_Event__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member</description>
    <label>Member</label>
    <referenceTo>FieloPLT__Member__c</referenceTo>
    <relationshipLabel>Chatter Events</relationshipLabel>
    <relationshipName>ChatterEvents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chatter_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Write a post</fullName>
            </value>
            <value>
                <fullName>Your answer is marked as best</fullName>
            </value>
            <value>
                <fullName>Receive a like</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/F_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>F_ExternalID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Type__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Type__c</fullName>
    <description>The type of Member: Individual (physical person or sole proprietorship), Organization Contributor Member (physical person contributing to an organization) or Organization Member (a company or entity).</description>
    <inlineHelpText>Choose what kind of Member this is: Individual (physical person or sole proprietorship), Organization Contributor Member (physical person contributing to an organization) or Organization Member (a company or entity).</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual Account</fullName>
                <default>true</default>
                <label>Individual Member</label>
            </value>
            <value>
                <fullName>Organization Account</fullName>
                <label>Organization Member</label>
            </value>
            <value>
                <fullName>Organization Contributor</fullName>
                <label>Organization Contributor Member</label>
            </value>
            <value>
                <fullName>Team</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Group_ID__c</fullName>
    <label>Group ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FieloSObjectFactory.cls
global with sharing class FieloSObjectFactory {
    
    global static String strNetworkId
	{
		get
		{
			return [SELECT Id FROM Network LIMIT 1][0].Id;
		}
	}

    public static Chatter_Event__c createEvent(Id memberId, Id groupId, String eventType, String groupName) {
        return new Chatter_Event__c(
            member__c = memberId,
            Group_ID__c = groupId,
            type__c = eventType,
            Group_Name__c = groupName
        );
    }
    
    public static Chatter_Event__c createEvent(Id memberId, Id groupId, String eventType, String groupName, Id feedId) {
        return new Chatter_Event__c(
            member__c = memberId,
            Group_ID__c = groupId,
            type__c = eventType,
            Group_Name__c = groupName,
            Feed_Item_Id__c = feedId
        );
    }
    
    public static FieloPLT__Member__c createGeneralMember(String email, String programId, Id userId, String name) {
        return new FieloPLT__Member__c(
            FieloPLT__Email__c = email,
            FieloPLT__Program__c = programId,
            FieloPLT__Type__c = 'Employee',
            FieloPLT__User__c = userId,
            Name = name,
            F_ExternalID__c = userId
        );
    }
    global static Id createTestGroup(Id ownerId, String groupName, List<User> users)
	{
		CollaborationGroup g = new CollaborationGroup(Name = groupName, CollaborationType = 'Public');
		g.OwnerId = ownerId;

		insert g;

		List<CollaborationGroupMember> groupMembers = new List<CollaborationGroupMember>();

		for (User user : users)
		{
			CollaborationGroupMember member = new CollaborationGroupMember();
			member.MemberId = user.Id ;
			member.CollaborationGroupId = g.Id ;
			groupMembers.add(member);
		}

		System.assertNotEquals(null, groupMembers);

		insert groupMembers;
		return g.Id ;
	}

	global static Id createTestGroup(String groupName)
	{
		CollaborationGroup myGroup = new CollaborationGroup();
		myGroup.Name               = groupName;
		myGroup.NetworkId          = strNetworkId;
		myGroup.CollaborationType  = 'Public'; //can be 'Public' or 'Private'

		System.assertNotEquals(null, myGroup);

		insert myGroup;
		return myGroup.Id;
	}
    public static User createStandardUserNoContact()//
	{
		List<Profile> standardProfileList = [SELECT Id FROM Profile WHERE Name = :Peak_Onboarding_TestConstants.COMMUNITY_PROFILE];
		User testUser;
		if (!(standardProfileList == null || standardProfileList.size() == 0))
		{
			Profile standardProfile = standardProfileList[0];
			testUser = new User(Alias = Peak_Onboarding_TestConstants.STANDARD_ALIAS, Email = Peak_Onboarding_TestConstants.STANDARD_EMAIL, EmailEncodingKey = Peak_Onboarding_TestConstants.ENCODING, FirstName = Peak_Onboarding_TestConstants.FIRSTNAME, LastName = Peak_Onboarding_TestConstants.LASTNAME, LanguageLocaleKey = Peak_Onboarding_TestConstants.LOCALE, LocaleSidKey = Peak_Onboarding_TestConstants.LOCALE, ProfileId = standardProfile.Id, TimeZoneSidKey = Peak_Onboarding_TestConstants.TIMEZONE, Username = Peak_Onboarding_TestConstants.STANDARD_USERNAME);
		}

		return testUser;
	}
    
    
}