force-app/main/default/objects/Chatter_Event__c/Chatter_Event__c.object-meta.xml
<CustomObject>
    <label>Chatter Event</label>
    <nameField>
        <label>Chatter Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chatter Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chatter_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Write a post</fullName>
            </value>
            <value>
                <fullName>Your answer is marked as best</fullName>
            </value>
            <value>
                <fullName>Receive a like</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/F_Leaderboard__c/F_Leaderboard__c.object-meta.xml
<CustomObject>
    <label>Leaderboard</label>
    <nameField>
        <displayFormat>L-{000000000}</displayFormat>
        <label>Leaderboard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaderboard</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/F_Leaderboard__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Week</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Transaction__c/fields/Chatter_Event__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Chatter Event</description>
    <label>Chatter Event</label>
    <referenceTo>Chatter_Event__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/F_PurgeBatch.cls
public with sharing class F_PurgeBatch implements Database.Batchable<sObject>, Database.Stateful{
        
    private Integer currentBatch;


    public F_PurgeBatch(){
        currentBatch = 0;
    }

    public F_PurgeBatch(integer current){
        currentBatch = current;
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        string q;
        if(currentBatch == 0)
        {
			q = 'SELECT ID FROM Chatter_Event__C WHERE CreatedDate = LAST_FISCAL_QUARTER';
        }
        if(currentBatch == 1)
        {
			q = 'Select ID FROM FieloPLT__Point__c WHERE CreatedDate = LAST_FISCAL_QUARTER';
        }
        if(currentBatch == 2)
        {
			q = 'Select ID FROM FieloPLT__Transaction__c WHERE CreatedDate = LAST_FISCAL_QUARTER';
        }
        if(currentBatch == 3)
        {
			q = 'Select ID FROM F_Leaderboard__c WHERE CreatedDate = LAST_FISCAL_QUARTER AND Type__c != \'Quarter\' ';
        }
        return Database.getQueryLocator(q);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope){
			delete scope;
    }

    public void finish(Database.BatchableContext BC){
            system.debug('####### FINISH #######');
    }


}