force-app/main/default/objects/FieloPLT__Member__c/fields/F_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>F_ExternalID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/FieloPLT__Type__c.field-meta.xml
<CustomField>
    <fullName>FieloPLT__Type__c</fullName>
    <description>The type of Member: Individual (physical person or sole proprietorship), Organization Contributor Member (physical person contributing to an organization) or Organization Member (a company or entity).</description>
    <inlineHelpText>Choose what kind of Member this is: Individual (physical person or sole proprietorship), Organization Contributor Member (physical person contributing to an organization) or Organization Member (a company or entity).</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual Account</fullName>
                <default>true</default>
                <label>Individual Member</label>
            </value>
            <value>
                <fullName>Organization Account</fullName>
                <label>Organization Member</label>
            </value>
            <value>
                <fullName>Organization Contributor</fullName>
                <label>Organization Contributor Member</label>
            </value>
            <value>
                <fullName>Team</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Group_ID__c</fullName>
    <label>Group ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/F_MemberCreationBatch.cls
global class F_MemberCreationBatch implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator( [SELECT Id, MemberId, Member.Name, Member.Email, CollaborationGroupId, CollaborationGroup.Name,CollaborationGroup.network.name, CollaborationRole FROM CollaborationGroupMember] );
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        System.debug('##### Execute');
        System.debug('##### List Size ' + scope.Size());
        List<CollaborationGroupMember> collbMemberList = (List<CollaborationGroupMember>) scope;
        List<FieloPLT__Member__c> memberList = new List<FieloPLT__Member__c>();
        
        List<FieloPLT__Program__c> programs = [SELECT Id, Name FROM FieloPLT__Program__c ]; 
        
        for(CollaborationGroupMember collab : collbMemberList){
            for(FieloPLT__Program__c  program : programs){
                if(program.name=='Chatter Incentive'){
                    FieloPLT__Member__c member = new FieloPLT__Member__c();
                    member.FieloPLT__Email__c = collab.Member.Email;
                    member.FieloPLT__Program__c = program.Id;
                    member.FieloPLT__Type__c = 'Employee';
                    member.FieloPLT__User__c = collab.MemberId;
                    member.Group_ID__c = collab.CollaborationGroupId;
                    member.Group_Name__c = collab.CollaborationGroup.Name;
                    member.Name = collab.Member.Name;   
                    member.F_ExternalID__c = collab.MemberId + '-' + collab.CollaborationGroupId;
                    memberList.add(member);
                  }
            }
        }   
        
        try {  
            if(memberList.size()>0)
            upsert memberList F_ExternalID__c;
        }catch (DmlException e) {
            System.debug(e.getMessage());
        }
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('#### finish');
    }
    
    
    
    
}