force-app/main/default/objects/FieloPLT__Member__c/fields/F_Level__c.field-meta.xml
<CustomField>
    <fullName>F_Level__c</fullName>
    <formula>FieloPLT__CurrentLevelMember__r.FieloPLT__Level__r.Name</formula>
    <label>Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieloPLT__Member__c/fields/Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Group_ID__c</fullName>
    <label>Group ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/F_MemberPointsByChatterGroup.cls
public with sharing class F_MemberPointsByChatterGroup {

    @AuraEnabled(cacheable=true)
    public static FieloPLT__Member__c getMemberByGroup(String groupId) {
        List<FieloPLT__Member__c> members = [SELECT Id, Name, Group_ID__c, FieloPLT__User__c, 
            FieloPLT__Points__c, Group_Name__c, F_Level__c  
            FROM FieloPLT__Member__c
            WHERE Group_ID__c = :groupId
            AND FieloPLT__User__c = :UserInfo.getUserId()];
        return members.isEmpty()?null:members[0];
    }
}